services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
      - ./frontend/media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db


  db:
    image: postgres:14
    container_name: ozdobione_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
