services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
      - ./frontend/media:/app/media
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: ozdobione_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

volumes:
  postgres_data: