# Generated by Django 5.1.5 on 2025-01-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embed_code',
            field=models.TextField(blank=True, null=True, verbose_name='Kod osadzenia'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL filmu (YouTube/Facebook)'),
        ),
    ]
