# Generated by Django 5.1.5 on 2025-01-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_video_embed_code_alter_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_tall',
            field=models.BooleanField(default=False, verbose_name='Czy filmik jest wysoki czy szeroki?'),
        ),
    ]
