# Generated by Django 5.1.5 on 2025-01-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_video_is_tall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_tall',
            field=models.BooleanField(default=False, verbose_name='Czy jest wysoki?'),
        ),
    ]
