# Generated by Django 5.1.5 on 2025-01-26 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_video_is_tall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_tall',
        ),
    ]
