# Generated by Django 5.1.5 on 2025-01-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_remove_video_is_tall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Zdjęcie', 'verbose_name_plural': 'Zdjęcia'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Filmy'},
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL filmu'),
        ),
    ]
