# Generated by Django 5.1.5 on 2025-01-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_tag_options_tag_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Pytanie')),
                ('answer', models.TextField(verbose_name='Odpowiedź')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
    ]
