# Generated by Django 5.1.5 on 2025-01-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'verbose_name': 'Pole formularza', 'verbose_name_plural': 'Pola formularza'},
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('char', 'Pole tekstowe'), ('email', 'Pole email'), ('phone', 'Pole telefoniczne'), ('textarea', 'Pole tekstowe (wielowierszowe)'), ('checkbox', 'Pole wyboru')], max_length=20, verbose_name='Typ pola'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Etykieta'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='required',
            field=models.BooleanField(default=True, verbose_name='Wymagane'),
        ),
    ]
