# Generated by Django 5.1.5 on 2025-01-26 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_formfield_options_formfield_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('char', 'Pole tekstowe'), ('email', 'Pole email'), ('phone', 'Pole telefoniczne'), ('textarea', 'Pole tekstowe (wielowierszowe)'), ('checkbox', 'Pole wyboru'), ('multiselect', 'Pole wielokrotnego wyboru')], max_length=20, verbose_name='Typ pola'),
        ),
        migrations.CreateModel(
            name='FormFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=100, verbose_name='Opcja')),
                ('form_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='form.formfield')),
            ],
            options={
                'verbose_name': 'Opcja pola formularza',
                'verbose_name_plural': 'Opcje pola formularza',
            },
        ),
    ]
