# Generated by Django 5.1.5 on 2025-01-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_formfield_field_type_formfieldoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa formularza')),
            ],
            options={
                'verbose_name': 'Typ formularza',
                'verbose_name_plural': 'Typy formularzy',
            },
        ),
        migrations.AddField(
            model_name='formfield',
            name='form_types',
            field=models.ManyToManyField(related_name='fields', to='form.formtype', verbose_name='Typy formularzy'),
        ),
    ]
