# Generated by Django 5.1.5 on 2025-01-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_formtype_formfield_form_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formtype',
            options={'ordering': ['order'], 'verbose_name': 'Typ formularza', 'verbose_name_plural': 'Typy formularzy'},
        ),
        migrations.AddField(
            model_name='formtype',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Kolejność'),
        ),
    ]
